2019-10-30 16:50:52 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[15]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-30 16:50:52 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Constraint "USERS_USUARIO_UNIQUE" already exists; SQL statement:
ALTER TABLE USERS ADD CONSTRAINT USERS_USUARIO_UNIQUE UNIQUE (USUARIO) [90045-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:103)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:98)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:89)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:31)
	at code.BaseDeDatos$agregaUsuario$1.invoke(BaseDeDatos.kt:8)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at code.BaseDeDatos.agregaUsuario(BaseDeDatos.kt:30)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:29)
	at view.RegisterController$tryRegister$1.invoke(RegisterController.kt:7)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
